[tool.black]
line-length = 100
target-version = ['py310']
fast = true

[tool.isort]
profile = "black"
extend_skip_glob = ["tests/**", "*.pyx", "testdata/**"]
skip_gitignore = true
line_length = 100
multi_line_output = 9
force_single_line = true
float_to_top = true

[tool.pylint.messages_control]
disable = "C0103,C0415"